tags: list[str] = [
    "sky",
    "beach",
    "waterfall",
    "night",
    "mountain",
    "sunset",
    "river",
    "landscape",
    "forest",
    "rain",
    "ocean",
    "sunrise",
    "skyline",
    "northern lights",
    "stars",
    "coral reef",
    "desktop background",
    "jungle",
    "desert",
    "cave",
    "volcano",
    "iceberg",
    "lake",
    "moon",
    "clouds",
    "aurora",
    "fog",
    "cityscape",
    "snow",
    "dawn",
    "dusk",
    "rainbow",
    "garden",
    "meadow",
    "cliff",
    "prairie",
    "seascape",
    "coast",
    "canyon",
    "fields",
    "mist",
    "waves",
    "urban",
    "rural",
    "trail",
    "wildflowers",
    "horizon",
    "grassland",
    "tundra",
    "savanna",
    "green fields",
    "farmland",
    "rice paddies",
    "vineyard",
    "orchard",
    "meadow",
    "pasture",
    "terraced fields",
    "crop rows",
    "gardening",
    "sprouts",
    "lush greenery",
    "vegetation",
    "wildflowers",
    "hillside farms",
    "harvest fields",
    "plantation",
    "greenhouse",
    "irrigation",
    "farm machinery in fields",
    "bamboo forest",
    "pine forest",
    "tropical foliage",
    "grasslands",
    "wheat fields",
    "cornfields",
    "sunlit fields",
    "morning dew on grass",
    "countryside",
    "rural landscape",
    "mustard field",
]

config: dict[str : str | int | float | list] = {
    "check_internet_connection": True,
    "run_after_every_hour": 16,
    "not_delete_from_last_day": 7,
    "tags": tags,
    "no_of_images_to_download": 2,
    "force_download": False,
    "log_file": "wallpaper_updator.log",
    "lock_file": "wallpaper_updator.lock",
    "last_run_file": "last_run.txt",
    "timeout": 20,
    "clear_images_data_after_days": 365 * 100,
}

if __name__ == "__main__":

    print(tags[22])
    print(tags.index("cliff"))
